apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: This is an example of a Flask application.
  annotations:
    github.com/project-slug: glisav/python-app
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
