apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: python-app
  description: This is an example of a Python application.
  annotations:
    github.com/project-slug: glisav/python-app
spec:
  type: service
  owner: development
  lifecycle: experimental
